/*
 * playit.gg's api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unstable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gg.playit.api.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import gg.playit.api.models.PortType;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AgentPendingTunnel
 */
public class AgentPendingTunnelTest {
    private final AgentPendingTunnel model = new AgentPendingTunnel();

    /**
     * Model tests for AgentPendingTunnel
     */
    @Test
    public void testAgentPendingTunnel() {
        // TODO: test AgentPendingTunnel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'proto'
     */
    @Test
    public void protoTest() {
        // TODO: test proto
    }

    /**
     * Test the property 'portCount'
     */
    @Test
    public void portCountTest() {
        // TODO: test portCount
    }

    /**
     * Test the property 'tunnelType'
     */
    @Test
    public void tunnelTypeTest() {
        // TODO: test tunnelType
    }

    /**
     * Test the property 'isDisabled'
     */
    @Test
    public void isDisabledTest() {
        // TODO: test isDisabled
    }

}
