/*
 * playit.gg's api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unstable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gg.playit.api.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import gg.playit.api.models.AgentAccountStatus;
import gg.playit.api.models.AgentPendingTunnel;
import gg.playit.api.models.AgentTunnel;
import gg.playit.api.models.AgentType;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AgentRunData
 */
public class AgentRunDataTest {
    private final AgentRunData model = new AgentRunData();

    /**
     * Model tests for AgentRunData
     */
    @Test
    public void testAgentRunData() {
        // TODO: test AgentRunData
    }

    /**
     * Test the property 'agentId'
     */
    @Test
    public void agentIdTest() {
        // TODO: test agentId
    }

    /**
     * Test the property 'agentType'
     */
    @Test
    public void agentTypeTest() {
        // TODO: test agentType
    }

    /**
     * Test the property 'accountStatus'
     */
    @Test
    public void accountStatusTest() {
        // TODO: test accountStatus
    }

    /**
     * Test the property 'tunnels'
     */
    @Test
    public void tunnelsTest() {
        // TODO: test tunnels
    }

    /**
     * Test the property 'pending'
     */
    @Test
    public void pendingTest() {
        // TODO: test pending
    }

}
