/*
 * playit.gg's api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unstable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gg.playit.api.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AllocatedPorts
 */
public class AllocatedPortsTest {
    private final AllocatedPorts model = new AllocatedPorts();

    /**
     * Model tests for AllocatedPorts
     */
    @Test
    public void testAllocatedPorts() {
        // TODO: test AllocatedPorts
    }

    /**
     * Test the property 'allowed'
     */
    @Test
    public void allowedTest() {
        // TODO: test allowed
    }

    /**
     * Test the property 'claimed'
     */
    @Test
    public void claimedTest() {
        // TODO: test claimed
    }

    /**
     * Test the property 'desired'
     */
    @Test
    public void desiredTest() {
        // TODO: test desired
    }

}
