/*
 * playit.gg's api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unstable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gg.playit.api.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssignedAgent
 */
public class AssignedAgentTest {
    private final AssignedAgent model = new AssignedAgent();

    /**
     * Model tests for AssignedAgent
     */
    @Test
    public void testAssignedAgent() {
        // TODO: test AssignedAgent
    }

    /**
     * Test the property 'agentId'
     */
    @Test
    public void agentIdTest() {
        // TODO: test agentId
    }

    /**
     * Test the property 'agentName'
     */
    @Test
    public void agentNameTest() {
        // TODO: test agentName
    }

    /**
     * Test the property 'localIp'
     */
    @Test
    public void localIpTest() {
        // TODO: test localIp
    }

    /**
     * Test the property 'localPort'
     */
    @Test
    public void localPortTest() {
        // TODO: test localPort
    }

}
