/*
 * playit.gg's api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unstable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gg.playit.api.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import gg.playit.api.models.PortType;
import gg.playit.api.models.TunnelCreateUseAllocation;
import gg.playit.api.models.TunnelOriginCreate;
import gg.playit.api.models.TunnelType;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReqTunnelsCreate
 */
public class ReqTunnelsCreateTest {
    private final ReqTunnelsCreate model = new ReqTunnelsCreate();

    /**
     * Model tests for ReqTunnelsCreate
     */
    @Test
    public void testReqTunnelsCreate() {
        // TODO: test ReqTunnelsCreate
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'tunnelType'
     */
    @Test
    public void tunnelTypeTest() {
        // TODO: test tunnelType
    }

    /**
     * Test the property 'portType'
     */
    @Test
    public void portTypeTest() {
        // TODO: test portType
    }

    /**
     * Test the property 'portCount'
     */
    @Test
    public void portCountTest() {
        // TODO: test portCount
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'alloc'
     */
    @Test
    public void allocTest() {
        // TODO: test alloc
    }

    /**
     * Test the property 'firewallId'
     */
    @Test
    public void firewallIdTest() {
        // TODO: test firewallId
    }

}
