/*
 * playit.gg's api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unstable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gg.playit.api.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SignedEpoch
 */
public class SignedEpochTest {
    private final SignedEpoch model = new SignedEpoch();

    /**
     * Model tests for SignedEpoch
     */
    @Test
    public void testSignedEpoch() {
        // TODO: test SignedEpoch
    }

    /**
     * Test the property 'epochSec'
     */
    @Test
    public void epochSecTest() {
        // TODO: test epochSec
    }

}
