/*
 * playit.gg's api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unstable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gg.playit.api.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TunnelsCreatePost400ResponseOneOfData
 */
public class TunnelsCreatePost400ResponseOneOfDataTest {
    private final TunnelsCreatePost400ResponseOneOfData model = new TunnelsCreatePost400ResponseOneOfData();

    /**
     * Model tests for TunnelsCreatePost400ResponseOneOfData
     */
    @Test
    public void testTunnelsCreatePost400ResponseOneOfData() {
        // TODO: test TunnelsCreatePost400ResponseOneOfData
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
