/*
 * playit.gg's api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unstable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gg.playit.api.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import gg.playit.JSON;

/**
 * AgentRouting
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AgentRouting {
  public static final String SERIALIZED_NAME_AGENT_ID = "agent_id";
  @SerializedName(SERIALIZED_NAME_AGENT_ID)
  private String agentId;

  public static final String SERIALIZED_NAME_TARGETS4 = "targets4";
  @SerializedName(SERIALIZED_NAME_TARGETS4)
  private List<String> targets4 = new ArrayList<>();

  public static final String SERIALIZED_NAME_TARGETS6 = "targets6";
  @SerializedName(SERIALIZED_NAME_TARGETS6)
  private List<String> targets6 = new ArrayList<>();

  public AgentRouting() {
  }

  public AgentRouting agentId(String agentId) {
    this.agentId = agentId;
    return this;
  }

   /**
   * Get agentId
   * @return agentId
  **/
  @javax.annotation.Nonnull
  public String getAgentId() {
    return agentId;
  }

  public void setAgentId(String agentId) {
    this.agentId = agentId;
  }


  public AgentRouting targets4(List<String> targets4) {
    this.targets4 = targets4;
    return this;
  }

  public AgentRouting addTargets4Item(String targets4Item) {
    if (this.targets4 == null) {
      this.targets4 = new ArrayList<>();
    }
    this.targets4.add(targets4Item);
    return this;
  }

   /**
   * Get targets4
   * @return targets4
  **/
  @javax.annotation.Nonnull
  public List<String> getTargets4() {
    return targets4;
  }

  public void setTargets4(List<String> targets4) {
    this.targets4 = targets4;
  }


  public AgentRouting targets6(List<String> targets6) {
    this.targets6 = targets6;
    return this;
  }

  public AgentRouting addTargets6Item(String targets6Item) {
    if (this.targets6 == null) {
      this.targets6 = new ArrayList<>();
    }
    this.targets6.add(targets6Item);
    return this;
  }

   /**
   * Get targets6
   * @return targets6
  **/
  @javax.annotation.Nonnull
  public List<String> getTargets6() {
    return targets6;
  }

  public void setTargets6(List<String> targets6) {
    this.targets6 = targets6;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentRouting agentRouting = (AgentRouting) o;
    return Objects.equals(this.agentId, agentRouting.agentId) &&
        Objects.equals(this.targets4, agentRouting.targets4) &&
        Objects.equals(this.targets6, agentRouting.targets6);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agentId, targets4, targets6);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentRouting {\n");
    sb.append("    agentId: ").append(toIndentedString(agentId)).append("\n");
    sb.append("    targets4: ").append(toIndentedString(targets4)).append("\n");
    sb.append("    targets6: ").append(toIndentedString(targets6)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("agent_id");
    openapiFields.add("targets4");
    openapiFields.add("targets6");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("agent_id");
    openapiRequiredFields.add("targets4");
    openapiRequiredFields.add("targets6");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AgentRouting
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AgentRouting.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AgentRouting is not found in the empty JSON string", AgentRouting.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AgentRouting.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AgentRouting` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AgentRouting.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("agent_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `agent_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("agent_id").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("targets4") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("targets4").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `targets4` to be an array in the JSON string but got `%s`", jsonObj.get("targets4").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("targets6") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("targets6").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `targets6` to be an array in the JSON string but got `%s`", jsonObj.get("targets6").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AgentRouting.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AgentRouting' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AgentRouting> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AgentRouting.class));

       return (TypeAdapter<T>) new TypeAdapter<AgentRouting>() {
           @Override
           public void write(JsonWriter out, AgentRouting value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AgentRouting read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AgentRouting given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AgentRouting
  * @throws IOException if the JSON string is invalid with respect to AgentRouting
  */
  public static AgentRouting fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AgentRouting.class);
  }

 /**
  * Convert an instance of AgentRouting to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

