/*
 * playit.gg's api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unstable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gg.playit.api.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import gg.playit.api.models.TunnelCreateUseAllocationOneOf;
import gg.playit.api.models.TunnelCreateUseAllocationOneOf1;
import gg.playit.api.models.TunnelCreateUseAllocationOneOf2;
import gg.playit.api.models.UseRegion;
import java.io.IOException;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import gg.playit.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-08T12:14:41.539310597-08:00[America/Los_Angeles]")
public class TunnelCreateUseAllocation extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(TunnelCreateUseAllocation.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!TunnelCreateUseAllocation.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'TunnelCreateUseAllocation' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<TunnelCreateUseAllocationOneOf> adapterTunnelCreateUseAllocationOneOf = gson.getDelegateAdapter(this, TypeToken.get(TunnelCreateUseAllocationOneOf.class));
            final TypeAdapter<TunnelCreateUseAllocationOneOf1> adapterTunnelCreateUseAllocationOneOf1 = gson.getDelegateAdapter(this, TypeToken.get(TunnelCreateUseAllocationOneOf1.class));
            final TypeAdapter<TunnelCreateUseAllocationOneOf2> adapterTunnelCreateUseAllocationOneOf2 = gson.getDelegateAdapter(this, TypeToken.get(TunnelCreateUseAllocationOneOf2.class));

            return (TypeAdapter<T>) new TypeAdapter<TunnelCreateUseAllocation>() {
                @Override
                public void write(JsonWriter out, TunnelCreateUseAllocation value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `TunnelCreateUseAllocationOneOf`
                    if (value.getActualInstance() instanceof TunnelCreateUseAllocationOneOf) {
                      JsonElement element = adapterTunnelCreateUseAllocationOneOf.toJsonTree((TunnelCreateUseAllocationOneOf)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    // check if the actual instance is of the type `TunnelCreateUseAllocationOneOf1`
                    if (value.getActualInstance() instanceof TunnelCreateUseAllocationOneOf1) {
                      JsonElement element = adapterTunnelCreateUseAllocationOneOf1.toJsonTree((TunnelCreateUseAllocationOneOf1)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    // check if the actual instance is of the type `TunnelCreateUseAllocationOneOf2`
                    if (value.getActualInstance() instanceof TunnelCreateUseAllocationOneOf2) {
                      JsonElement element = adapterTunnelCreateUseAllocationOneOf2.toJsonTree((TunnelCreateUseAllocationOneOf2)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: TunnelCreateUseAllocationOneOf, TunnelCreateUseAllocationOneOf1, TunnelCreateUseAllocationOneOf2");
                }

                @Override
                public TunnelCreateUseAllocation read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize TunnelCreateUseAllocationOneOf
                    try {
                      // validate the JSON object to see if any exception is thrown
                      TunnelCreateUseAllocationOneOf.validateJsonElement(jsonElement);
                      actualAdapter = adapterTunnelCreateUseAllocationOneOf;
                      match++;
                      log.log(Level.FINER, "Input data matches schema 'TunnelCreateUseAllocationOneOf'");
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for TunnelCreateUseAllocationOneOf failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'TunnelCreateUseAllocationOneOf'", e);
                    }
                    // deserialize TunnelCreateUseAllocationOneOf1
                    try {
                      // validate the JSON object to see if any exception is thrown
                      TunnelCreateUseAllocationOneOf1.validateJsonElement(jsonElement);
                      actualAdapter = adapterTunnelCreateUseAllocationOneOf1;
                      match++;
                      log.log(Level.FINER, "Input data matches schema 'TunnelCreateUseAllocationOneOf1'");
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for TunnelCreateUseAllocationOneOf1 failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'TunnelCreateUseAllocationOneOf1'", e);
                    }
                    // deserialize TunnelCreateUseAllocationOneOf2
                    try {
                      // validate the JSON object to see if any exception is thrown
                      TunnelCreateUseAllocationOneOf2.validateJsonElement(jsonElement);
                      actualAdapter = adapterTunnelCreateUseAllocationOneOf2;
                      match++;
                      log.log(Level.FINER, "Input data matches schema 'TunnelCreateUseAllocationOneOf2'");
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for TunnelCreateUseAllocationOneOf2 failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'TunnelCreateUseAllocationOneOf2'", e);
                    }

                    if (match == 1) {
                        TunnelCreateUseAllocation ret = new TunnelCreateUseAllocation();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for TunnelCreateUseAllocation: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public TunnelCreateUseAllocation() {
        super("oneOf", Boolean.FALSE);
    }

    public TunnelCreateUseAllocation(TunnelCreateUseAllocationOneOf o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public TunnelCreateUseAllocation(TunnelCreateUseAllocationOneOf1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public TunnelCreateUseAllocation(TunnelCreateUseAllocationOneOf2 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("TunnelCreateUseAllocationOneOf", TunnelCreateUseAllocationOneOf.class);
        schemas.put("TunnelCreateUseAllocationOneOf1", TunnelCreateUseAllocationOneOf1.class);
        schemas.put("TunnelCreateUseAllocationOneOf2", TunnelCreateUseAllocationOneOf2.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return TunnelCreateUseAllocation.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * TunnelCreateUseAllocationOneOf, TunnelCreateUseAllocationOneOf1, TunnelCreateUseAllocationOneOf2
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof TunnelCreateUseAllocationOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TunnelCreateUseAllocationOneOf1) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TunnelCreateUseAllocationOneOf2) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be TunnelCreateUseAllocationOneOf, TunnelCreateUseAllocationOneOf1, TunnelCreateUseAllocationOneOf2");
    }

    /**
     * Get the actual instance, which can be the following:
     * TunnelCreateUseAllocationOneOf, TunnelCreateUseAllocationOneOf1, TunnelCreateUseAllocationOneOf2
     *
     * @return The actual instance (TunnelCreateUseAllocationOneOf, TunnelCreateUseAllocationOneOf1, TunnelCreateUseAllocationOneOf2)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `TunnelCreateUseAllocationOneOf`. If the actual instance is not `TunnelCreateUseAllocationOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TunnelCreateUseAllocationOneOf`
     * @throws ClassCastException if the instance is not `TunnelCreateUseAllocationOneOf`
     */
    public TunnelCreateUseAllocationOneOf getTunnelCreateUseAllocationOneOf() throws ClassCastException {
        return (TunnelCreateUseAllocationOneOf)super.getActualInstance();
    }
    /**
     * Get the actual instance of `TunnelCreateUseAllocationOneOf1`. If the actual instance is not `TunnelCreateUseAllocationOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TunnelCreateUseAllocationOneOf1`
     * @throws ClassCastException if the instance is not `TunnelCreateUseAllocationOneOf1`
     */
    public TunnelCreateUseAllocationOneOf1 getTunnelCreateUseAllocationOneOf1() throws ClassCastException {
        return (TunnelCreateUseAllocationOneOf1)super.getActualInstance();
    }
    /**
     * Get the actual instance of `TunnelCreateUseAllocationOneOf2`. If the actual instance is not `TunnelCreateUseAllocationOneOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TunnelCreateUseAllocationOneOf2`
     * @throws ClassCastException if the instance is not `TunnelCreateUseAllocationOneOf2`
     */
    public TunnelCreateUseAllocationOneOf2 getTunnelCreateUseAllocationOneOf2() throws ClassCastException {
        return (TunnelCreateUseAllocationOneOf2)super.getActualInstance();
    }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TunnelCreateUseAllocation
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    // validate oneOf schemas one by one
    int validCount = 0;
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with TunnelCreateUseAllocationOneOf
    try {
      TunnelCreateUseAllocationOneOf.validateJsonElement(jsonElement);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for TunnelCreateUseAllocationOneOf failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with TunnelCreateUseAllocationOneOf1
    try {
      TunnelCreateUseAllocationOneOf1.validateJsonElement(jsonElement);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for TunnelCreateUseAllocationOneOf1 failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with TunnelCreateUseAllocationOneOf2
    try {
      TunnelCreateUseAllocationOneOf2.validateJsonElement(jsonElement);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for TunnelCreateUseAllocationOneOf2 failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    if (validCount != 1) {
      throw new IOException(String.format("The JSON string is invalid for TunnelCreateUseAllocation with oneOf schemas: TunnelCreateUseAllocationOneOf, TunnelCreateUseAllocationOneOf1, TunnelCreateUseAllocationOneOf2. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
    }
  }

 /**
  * Create an instance of TunnelCreateUseAllocation given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TunnelCreateUseAllocation
  * @throws IOException if the JSON string is invalid with respect to TunnelCreateUseAllocation
  */
  public static TunnelCreateUseAllocation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TunnelCreateUseAllocation.class);
  }

 /**
  * Convert an instance of TunnelCreateUseAllocation to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

