/*
 * playit.gg's api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unstable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package gg.playit.api.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets TunnelDomainSource
 */
@JsonAdapter(TunnelDomainSource.Adapter.class)
public enum TunnelDomainSource {
  
  IP("from-ip"),
  
  TUNNEL("from-tunnel"),
  
  AGENT_IP("from-agent-ip");

  private String value;

  TunnelDomainSource(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TunnelDomainSource fromValue(String value) {
    for (TunnelDomainSource b : TunnelDomainSource.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TunnelDomainSource> {
    @Override
    public void write(final JsonWriter jsonWriter, final TunnelDomainSource enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TunnelDomainSource read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TunnelDomainSource.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    TunnelDomainSource.fromValue(value);
  }
}

